# Generated by Django 3.1.4 on 2020-12-21 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vacina_estabelecimento',
            new_name='VacinaEstabelecimento',
        ),
    ]
