# Generated by Django 3.1.4 on 2020-12-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201221_1853'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VacinaEstabelecimento',
            new_name='Vacina_Estabelecimento',
        ),
    ]
