# Generated by Django 3.1.4 on 2020-12-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_coordenador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UF', models.IntegerField()),
                ('Nome_UF', models.CharField(blank=True, max_length=1000)),
                ('Codigo_Municipio', models.CharField(max_length=100)),
                ('Nome_Municipio', models.CharField(max_length=1000)),
            ],
        ),
    ]
