# Generated by Django 3.1.4 on 2020-12-17 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_carteiravacinacao_estabelecimento_vacina'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='estabelecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estabelecimento'),
        ),
    ]
