# Generated by Django 3.1.4 on 2020-12-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profissional_estabelecimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento',
            name='vacina',
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='vacinas',
            field=models.ManyToManyField(to='api.Vacina', verbose_name='Vacinas do Estabelecimento'),
        ),
    ]
