# Generated by Django 3.1.4 on 2020-12-17 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201217_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carteiravacinacao',
            name='vacina',
        ),
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateField(null=True)),
                ('carteiraVacinacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.carteiravacinacao')),
                ('vacina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacina_carteira', to='api.vacina')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paciente')),
            ],
        ),
    ]
